version = 1

[merge]
require_automerge_label = false
blacklist_labels = ["In Progress"]
method = "squash"
delete_branch_on_merge = true
block_on_reviews_requested = false
notify_on_conflict = true
optimistic_updates = true
update_branch_immediately = true

[merge.message]
title = "pull_request_title"
include_pr_number = true
body_type = "markdown"